language: emacs-lisp

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq
      emacs24-nox emacs24-el emacs24-common-non-dfsg

  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-nox;
    fi

env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot

script:
  - make test
  - curl -fsSkL https://raw.github.com/rejeep/cask.el/master/go | sh
